"use client";
import Link from "next/link";
import {useState} from "react";
type Day = [string,string,string,string[],string];
const days:Day[]=[
 ["11/4 週三","抵達青森","青森機場 → 青森站 → 飯店",["抵達後以計程車或包車直達飯店，避免拖行李轉車。","下午安排 A-FACTORY 與青森站周邊，依體力彈性調整。","晚餐後提早回飯店休息。"],"首日完全不塞景點，保留航班延誤與爸媽休息時間。"],
 ["11/5 週四","青森市：海灣與睡魔","飯店 → 睡魔之家 WA RASSE → ASPAM → 淺蟲溫泉",["上午參觀睡魔之家，室內平坦動線約 60–90 分鐘。","中午於 A-FACTORY／ASPAM 用餐與採買。","下午前往淺蟲溫泉；海邊視風勢短暫停留。"],"11 月海風冷，請準備防風外套與保暖帽。"],
 ["11/6 週五","弘前：城下町秋色","青森 → 弘前公園 → 津輕藩睡魔村 → 弘前飯店",["退房後包車前往弘前，行李直接寄放飯店。","弘前公園只走追手門—杉之大橋—天守短線。","下午在津輕藩睡魔村看祭典文化與三味線。"],"落葉與濕地易滑，建議爸媽穿防滑鞋，不追求走完全園。"],
 ["11/7 週六","岩木山／弘前：蘋果與溫泉","弘前 → 蘋果公園 → 岩木山麓／嶽溫泉 → 弘前",["上午蘋果公園，採果是否開放以當日公告為準。","天候佳再到岩木山麓；雨雪改市區觀光館與咖啡店。","傍晚泡湯、早晚餐，為返程保留體力。"],"山區 11 月可能初雪；依司機路況調整，不勉強上山。"],
 ["11/8 週日","回程","弘前 → 青森機場／新青森站",["早餐後退房，包車前往機場或新青森站。","最後採買蘋果汁、蘋果派與海鮮煎餅。","由弘前出發至少預留 3 小時交通緩衝。"],"國際線請提早 2.5–3 小時抵達機場。"]
];
export default function Aomori(){const [n,setN]=useState(0);const d=days[n];return <main className="appShell googleTravelShell" style={{"--travel-bg":"url('https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=2200&q=88')"} as React.CSSProperties}><section className="hero googleTravelHero"><div className="googleHeroCopy"><nav className="mb-4 flex gap-2 text-sm"><Link className="rounded-full bg-white/20 px-3 py-1" href="/">🇳🇿 紐西蘭</Link><Link className="rounded-full bg-white/20 px-3 py-1" href="/aomori">🇯🇵 日本・青森</Link></nav><small>JAPAN · AOMORI · 2026/11/4–11/8</small><h1>青森慢旅・家人同行</h1><p>4 人同行｜70 歲長輩友善｜包車／計程車優先</p></div><div className="summaryCards googleSummaryCards"><article><small>📅 行程</small><strong>5 日</strong></article><article><small>👨‍👩‍👧‍👦 成員</small><strong>4 人</strong></article><article><small>🚐 移動</small><strong>包車優先</strong></article><article><small>❄️ 季節</small><strong>初冬</strong></article></div></section><section className="toolsPanel"><h2>每日行程</h2><div className="daySelector">{days.map((x,i)=><button key={x[0]} className={n===i?"active":""} onClick={()=>setN(i)}>DAY {i+1}<small>{x[0]}</small></button>)}</div><article className="answer"><small>{d[0]}</small><h2>{d[1]}</h2><p><b>移動：</b>{d[2]}</p><ol>{(d[3] as string[]).map(x=><li key={x}>{x}</li>)}</ol><p><b>長輩提醒：</b>{d[4]}</p></article></section><section className="toolsPanel"><h2>Travel ME AI 工具</h2><div className="summaryCards"><article><small>🛍️</small><strong>AI 購物顧問</strong><p>分析價格、預算與行李重量。</p></article><article><small>🍷</small><strong>AI 酒類顧問</strong><p>依餐點、口味與送禮需求推薦。</p></article><article><small>🌐</small><strong>AI 翻譯</strong><p>菜單、標籤與警語即時整理。</p></article><article><small>🏞️</small><strong>景點導覽</strong><p>歷史背景、停留與拍照提醒。</p></article></div></section></main>}
