"use client";
import Link from "next/link";
import {useState} from "react";
import {DayRouteMap} from "../../components/map/DayRouteMap";
import {aomoriRouteStops} from "../../data/jp/aomoriRouteStops";
type Day = [string,string,string,string[],string];
const driveTimes=["青森機場→弘前約 60–75 分鐘","弘前→蘋果公園約 15 分鐘；→奧入瀨約 2 小時；溪流→十和田湖約 1 小時","十和田湖→八甲田約 1.5 小時；→青森約 1 小時","青森站周邊景點步行 5–15 分鐘，可不動車","ASPAM→青森機場約 25 分鐘；→新青森站約 10 分鐘"];
const days:Day[]=[
 ["11/4 週三","抵達青森 → 弘前市區","青森機場取車 → 弘前公園 → 藤田紀念庭園 → 弘前溫泉飯店",["抵達青森機場後取車，直接前往弘前；不安排青森市區繞行。","弘前公園參加菊與紅葉祭；體力不足時先保留公園主線。","藤田紀念庭園喝下午茶，晚上入住弘前市區溫泉飯店。"],"若 14:30 後才抵達弘前，藤田紀念庭園改為備案；第一天不勉強趕景點。"],
 ["11/5 週四","弘前 → 奧入瀨溪流 → 十和田湖","弘前市蘋果公園 → 阿修羅之流 → 銚子大瀑布 → 十和田湖畔",["上午先到弘前市蘋果公園；採果依當日開放狀況。","再開車前往奧入瀨溪流，只停阿修羅之流與銚子大瀑布兩個定點。","傍晚入住十和田湖畔溫泉旅館或溪流飯店。"],"這是全程最長車程日，途中安排道の駅／休息站；不走完整溪流。"],
 ["11/6 週五","十和田湖 → 八甲田山麓 → 青森市","十和田湖畔 → 十和田神社／乙女之像 → 酸湯溫泉或城倉大橋 → 青森",["清晨在十和田湖畔散步，參拜十和田神社與乙女之像。","天氣晴朗且無強風才搭八甲田纜車；若停駛改酸湯溫泉或城倉大橋。","傍晚入住青森市區飯店，還車安排依 Day 5 航班調整。"],"山區可能初雪結冰，雪胎必備；纜車是天候備案，不硬上山。"],
 ["11/7 週六","岩木山／弘前：蘋果與溫泉","弘前 → 蘋果公園 → 岩木山麓／嶽溫泉 → 弘前",["上午蘋果公園，採果是否開放以當日公告為準。","天候佳再到岩木山麓；雨雪改市區觀光館與咖啡店。","傍晚泡湯、早晚餐，為返程保留體力。"],"山區 11 月可能初雪；依司機路況調整，不勉強上山。"],
 ["11/8 週日","回程","弘前 → 青森機場／新青森站",["早餐後退房，包車前往機場或新青森站。","最後採買蘋果汁、蘋果派與海鮮煎餅。","由弘前出發至少預留 3 小時交通緩衝。"],"國際線請提早 2.5–3 小時抵達機場。"]
];
export default function Aomori(){const [n,setN]=useState(0);const d=days[n];return <main className="appShell googleTravelShell" style={{"--travel-bg":"url('https://images.unsplash.com/photo-1545569341-9eb8b30979d9?auto=format&fit=crop&w=2200&q=88')"} as React.CSSProperties}><section className="hero googleTravelHero"><div className="googleHeroCopy"><nav className="mb-4 flex gap-2 text-sm"><Link className="rounded-full bg-white/20 px-3 py-1" href="/">🇳🇿 紐西蘭</Link><Link className="rounded-full bg-white/20 px-3 py-1" href="/aomori">🇯🇵 日本・青森</Link></nav><small>JAPAN · AOMORI · 2026/11/4–11/8</small><h1>青森慢旅・家人同行</h1><p>4 人同行｜70 歲長輩友善｜自駕／租車優先</p></div><div className="summaryCards googleSummaryCards"><article><small>📅 行程</small><strong>5 日</strong></article><article><small>👨‍👩‍👧‍👦 成員</small><strong>4 人</strong></article><article><small>🚐 移動</small><strong>包車優先</strong></article><article><small>❄️ 季節</small><strong>初冬</strong></article></div></section><section className="toolsPanel"><h2>每日行程</h2><div className="daySelector">{days.map((x,i)=><button key={x[0]} className={n===i?"active":""} onClick={()=>setN(i)}>DAY {i+1}<small>{x[0]}</small></button>)}</div><article className="answer"><small>{d[0]}</small><h2>{d[1]}</h2><p><b>自駕路線：</b>{d[2]}</p><p><b>預估車程：</b>{driveTimes[n]}</p><ol>{(d[3] as string[]).map(x=><li key={x}>{x}</li>)}</ol><p><b>長輩提醒：</b>{d[4]}</p></article></section><DayRouteMap day={n+1} stops={aomoriRouteStops}/><section className="toolsPanel"><h2>Travel ME AI 工具</h2><div className="summaryCards"><article><small>🛍️</small><strong>AI 購物顧問</strong><p>分析價格、預算與行李重量。</p></article><article><small>🍷</small><strong>AI 酒類顧問</strong><p>依餐點、口味與送禮需求推薦。</p></article><article><small>🌐</small><strong>AI 翻譯</strong><p>菜單、標籤與警語即時整理。</p></article><article><small>🏞️</small><strong>景點導覽</strong><p>歷史背景、停留與拍照提醒。</p></article></div></section></main>}
